apiVersion: v1
kind: Pod
metadata:
  name: wordpress-demo
  labels: 
    name: wordpress
spec: 
  containers: 
    - image: wordpress
      name: wordpress-demo
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
        - name: WORDPRESS_DB_PASSWORD
          value: yourpassword
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.0
      ports: 
        - containerPort: 80
          hostPort: 80
    - name: mysql
      image: mysql:5.5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword 
      ports:
        - containerPort: 3306
          hostPort: 3306
